# <center>カスタム層とSubclassing API</center>

In [2]:
import numpy as np
import matplotlib.pyplot as plt

# 1.カスタム層

単純なカスタム層を実装してみる

In [3]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

class CustomLayer(layers.Layer):
    def __init__(self, width, **kwargs):
        super().__init__(**kwargs)
        self.width = width

    def build(self, batch_input_shape):
        self.kernel = self.add_weight(shape=[batch_input_shape[-1],self.width],
            initializer='glorot_normal')
        super().build(batch_input_shape)

    def call(self, X):
        return X @ self.kernel

これを使った一層モデル

In [4]:
inputs = layers.Input(shape=(3,))
x = CustomLayer(5)(inputs)
model = keras.Model(inputs=inputs, outputs=x)

model.summary()

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 3)]               0         
_________________________________________________________________
custom_layer (CustomLayer)   (None, 5)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


で次のような人工データをフィッティングしてみる：

In [5]:
X = np.random.randn(3*100).reshape((100,3))
W = np.random.randn(3*5).reshape((3,5))
Y =  X@W

もちろんうまくいけばこのデータを作るのに使用した行列Wとモデルの重み行列は一致するはずである。

学習させてみよう：

In [6]:
model.compile(optimizer='adam', loss='mse')
model.fit(X,Y,epochs=500)

Epoch 1/500
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
4/4 [==============================] - 0s 3ms/step - loss: 2.4249
Epoch 2/500
4/4 [==============================] - 0s 2ms/step - loss: 2.4098
Epoch 3/500
4/4 [==============================] - 0s 2ms/step - loss: 2.3952
Epoch 4/500
4/4 [==============================] - 0s 2ms/step - loss: 2.3809
Epoch 5/500
4/4 [==============================] - 0s 2ms/step - loss: 2.3664
Epoch 6/500
4/4 [==============================] - 0s 2ms/step - loss: 2.3517
Epoch 7/500
4/4 [==============================] - 0s 2ms/step - loss: 2.3373
Epoch 8/500
4/4 [==============================] - 0s 2ms/step - loss: 2.3227
Epoch 9/500
4/4 [==============================] - 0s 2ms/step - 

4/4 [==============================] - 0s 2ms/step - loss: 1.3744
Epoch 100/500
4/4 [==============================] - 0s 2ms/step - loss: 1.3669
Epoch 101/500
4/4 [==============================] - 0s 2ms/step - loss: 1.3589
Epoch 102/500
4/4 [==============================] - 0s 2ms/step - loss: 1.3513
Epoch 103/500
4/4 [==============================] - 0s 2ms/step - loss: 1.3433
Epoch 104/500
4/4 [==============================] - 0s 2ms/step - loss: 1.3358
Epoch 105/500
4/4 [==============================] - 0s 2ms/step - loss: 1.3281
Epoch 106/500
4/4 [==============================] - 0s 2ms/step - loss: 1.3206
Epoch 107/500
4/4 [==============================] - 0s 2ms/step - loss: 1.3131
Epoch 108/500
4/4 [==============================] - 0s 2ms/step - loss: 1.3056
Epoch 109/500
4/4 [==============================] - 0s 2ms/step - loss: 1.2981
Epoch 110/500
4/4 [==============================] - 0s 2ms/step - loss: 1.2908
Epoch 111/500
4/4 [==============================] - 0

4/4 [==============================] - 0s 2ms/step - loss: 0.8029
Epoch 202/500
4/4 [==============================] - 0s 2ms/step - loss: 0.7988
Epoch 203/500
4/4 [==============================] - 0s 2ms/step - loss: 0.7948
Epoch 204/500
4/4 [==============================] - 0s 3ms/step - loss: 0.7907
Epoch 205/500
4/4 [==============================] - 0s 2ms/step - loss: 0.7866
Epoch 206/500
4/4 [==============================] - 0s 2ms/step - loss: 0.7826
Epoch 207/500
4/4 [==============================] - 0s 2ms/step - loss: 0.7787
Epoch 208/500
4/4 [==============================] - 0s 2ms/step - loss: 0.7748
Epoch 209/500
4/4 [==============================] - 0s 2ms/step - loss: 0.7708
Epoch 210/500
4/4 [==============================] - 0s 2ms/step - loss: 0.7671
Epoch 211/500
4/4 [==============================] - 0s 3ms/step - loss: 0.7630
Epoch 212/500
4/4 [==============================] - 0s 2ms/step - loss: 0.7591
Epoch 213/500
4/4 [==============================] - 0

4/4 [==============================] - 0s 2ms/step - loss: 0.4883
Epoch 304/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4860
Epoch 305/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4835
Epoch 306/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4814
Epoch 307/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4792
Epoch 308/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4769
Epoch 309/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4747
Epoch 310/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4725
Epoch 311/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4702
Epoch 312/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4680
Epoch 313/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4658
Epoch 314/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4637
Epoch 315/500
4/4 [==============================] - 0

4/4 [==============================] - 0s 2ms/step - loss: 0.3036
Epoch 406/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3021
Epoch 407/500
4/4 [==============================] - 0s 2ms/step - loss: 0.3006
Epoch 408/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2992
Epoch 409/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2978
Epoch 410/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2964
Epoch 411/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2950
Epoch 412/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2937
Epoch 413/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2924
Epoch 414/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2911
Epoch 415/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2897
Epoch 416/500
4/4 [==============================] - 0s 2ms/step - loss: 0.2885
Epoch 417/500
4/4 [==============================] - 0

学習済みのカスタム層の重みを見てみると、その値は

In [7]:
model.layers[1].kernel

<tf.Variable 'custom_layer/Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[-0.8135924 , -0.35792333,  0.31770974, -0.10829994, -0.85908455],
       [ 0.22043182, -0.74657756,  0.7619737 , -0.0686098 , -0.4109547 ],
       [-0.49477935,  0.00337849, -0.27877408, -0.21816745, -0.11422411]],
      dtype=float32)>

テンソルではなく、数値だけ見たければ

In [8]:
model.layers[1].kernel.numpy()

array([[-0.8135924 , -0.35792333,  0.31770974, -0.10829994, -0.85908455],
       [ 0.22043182, -0.74657756,  0.7619737 , -0.0686098 , -0.4109547 ],
       [-0.49477935,  0.00337849, -0.27877408, -0.21816745, -0.11422411]],
      dtype=float32)

データの作成に使った行列と比べてみると

In [9]:
W

array([[-0.74276554, -0.35606192,  0.31476038, -0.12115773, -0.95865184],
       [ 0.21848153, -0.7479374 ,  0.77823875, -0.06980771, -0.39329028],
       [-1.53891162, -0.00215691, -0.27801509, -0.21556816, -0.09887993]])

# 2. サブクラス化API

次に基底Modelクラスを継承してカスタムモデルを作ってみよう。と言っても、簡単なことをしているうちは今までのfunctional API的なモデルを一つにまとめたような感じしか受けないでしょう。

In [10]:
class SimpleModel(keras.Model):
    def __init__(self, width=5, **kwargs):
        super(SimpleModel, self).__init__(**kwargs)
        self.hidden = CustomLayer(width)

    def call(self, inputs):
        outputs = self.hidden(inputs)
        return outputs

大きなポイントは、入力層を用意する必要がない、あらわに入力サイズを指定する必要がないという点です。そのためにモデル作成時に自動でshapeのチェックをすることができません。また、同時にモデルの構造がcall()メソッドの中で定義されているので、構造が外から見えなくなってしまいます。このような不自由な点があるため、普段はfunctional APIを使っておくのが良いでしょう（今までのようにモデルを作るのでは事足りない時にSubclassing APIを使いましょう。つまり例えばモデルの構造が入力によって条件分岐して変わるようなダイナミックなモデルです。このようなモデルは、Subclassing APIのcall()メソッドの柔軟性を活用すると綺麗に実装・利用できます）。

いずれにせよ、モデルのインスタンスは普通に作成でき

In [11]:
model = SimpleModel(5)

学習もいつも通りです：

In [12]:
model.compile(optimizer='adam', loss='mse')
model.fit(X,Y,epochs=500)

Epoch 1/500
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
4/4 [==============================] - 0s 2ms/step - loss: 2.1147
Epoch 2/500
4/4 [==============================] - 0s 2ms/step - loss: 2.0978
Epoch 3/500
4/4 [==============================] - 0s 2ms/step - loss: 2.0820
Epoch 4/500
4/4 [==============================] - 0s 2ms/step - loss: 2.0658
Epoch 5/500
4/4 [==============================] - 0s 2ms/step - l

4/4 [==============================] - 0s 2ms/step - loss: 1.0618
Epoch 94/500
4/4 [==============================] - 0s 2ms/step - loss: 1.0533
Epoch 95/500
4/4 [==============================] - 0s 2ms/step - loss: 1.0445
Epoch 96/500
4/4 [==============================] - 0s 2ms/step - loss: 1.0361
Epoch 97/500
4/4 [==============================] - 0s 2ms/step - loss: 1.0277
Epoch 98/500
4/4 [==============================] - 0s 2ms/step - loss: 1.0191
Epoch 99/500
4/4 [==============================] - 0s 2ms/step - loss: 1.0108
Epoch 100/500
4/4 [==============================] - 0s 2ms/step - loss: 1.0023
Epoch 101/500
4/4 [==============================] - 0s 2ms/step - loss: 0.9944
Epoch 102/500
4/4 [==============================] - 0s 2ms/step - loss: 0.9869
Epoch 103/500
4/4 [==============================] - 0s 2ms/step - loss: 0.9789
Epoch 104/500
4/4 [==============================] - 0s 2ms/step - loss: 0.9710
Epoch 105/500
4/4 [==============================] - 0s 2ms/

4/4 [==============================] - 0s 2ms/step - loss: 0.4644
Epoch 196/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4605
Epoch 197/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4566
Epoch 198/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4527
Epoch 199/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4489
Epoch 200/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4449
Epoch 201/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4410
Epoch 202/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4368
Epoch 203/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4328
Epoch 204/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4293
Epoch 205/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4252
Epoch 206/500
4/4 [==============================] - 0s 2ms/step - loss: 0.4216
Epoch 207/500
4/4 [==============================] - 0

4/4 [==============================] - 0s 2ms/step - loss: 0.1868
Epoch 298/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1849
Epoch 299/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1831
Epoch 300/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1813
Epoch 301/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1796
Epoch 302/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1779
Epoch 303/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1762
Epoch 304/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1745
Epoch 305/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1729
Epoch 306/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1712
Epoch 307/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1696
Epoch 308/500
4/4 [==============================] - 0s 2ms/step - loss: 0.1681
Epoch 309/500
4/4 [==============================] - 0

4/4 [==============================] - 0s 2ms/step - loss: 0.0681
Epoch 400/500
4/4 [==============================] - 0s 2ms/step - loss: 0.0674
Epoch 401/500
4/4 [==============================] - 0s 2ms/step - loss: 0.0667
Epoch 402/500
4/4 [==============================] - 0s 2ms/step - loss: 0.0661
Epoch 403/500
4/4 [==============================] - 0s 2ms/step - loss: 0.0654
Epoch 404/500
4/4 [==============================] - 0s 2ms/step - loss: 0.0647
Epoch 405/500
4/4 [==============================] - 0s 2ms/step - loss: 0.0641
Epoch 406/500
4/4 [==============================] - 0s 2ms/step - loss: 0.0634
Epoch 407/500
4/4 [==============================] - 0s 2ms/step - loss: 0.0628
Epoch 408/500
4/4 [==============================] - 0s 2ms/step - loss: 0.0621
Epoch 409/500
4/4 [==============================] - 0s 2ms/step - loss: 0.0615
Epoch 410/500
4/4 [==============================] - 0s 2ms/step - loss: 0.0608
Epoch 411/500
4/4 [==============================] - 0

カスタムモデルクラスには入力層はないので、次の引数が変わることに注意

In [13]:
model.layers[0].kernel

<tf.Variable 'simple_model/custom_layer_1/Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[-6.3364673e-01, -3.5568199e-01,  3.1749016e-01, -8.2521416e-02,
        -6.8312794e-01],
       [ 6.5594546e-02, -7.4798149e-01,  7.7300370e-01, -7.5341575e-02,
        -4.0226352e-01],
       [-1.4779352e+00, -8.3356752e-04, -2.7844724e-01, -2.2212110e-01,
        -1.4875691e-01]], dtype=float32)>

当然、学習結果はほとんど変わらない。

# 発展問題
CapsuleNetをSubclassing APIで実装してみよう。

In [14]:
(keras.Model).__mro__

(tensorflow.python.keras.engine.training.Model,
 tensorflow.python.keras.engine.base_layer.Layer,
 tensorflow.python.module.module.Module,
 tensorflow.python.training.tracking.tracking.AutoTrackable,
 tensorflow.python.training.tracking.base.Trackable,
 tensorflow.python.keras.utils.version_utils.LayerVersionSelector,
 tensorflow.python.keras.utils.version_utils.ModelVersionSelector,
 object)

In [15]:
(keras.layers.Layer).__mro__

(tensorflow.python.keras.engine.base_layer.Layer,
 tensorflow.python.module.module.Module,
 tensorflow.python.training.tracking.tracking.AutoTrackable,
 tensorflow.python.training.tracking.base.Trackable,
 tensorflow.python.keras.utils.version_utils.LayerVersionSelector,
 object)